wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1670244849.418672
    t:
      1:
      - 5
      - 28
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 28
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.5
      8:
      - 3
      - 5
